{% set version = "0.4.0" %}
{% set name = "iembot" %}

package:
  name: iembot
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iembot-{{ version }}.tar.gz
  sha256: a090e60c2b78d1fee5ee2e3cb8d60c88663727d128f3f8c31370b98cde900530

build:
  entry_points:
    - iembot = iembot.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - atproto
    - click
    - feedgen
    - httpx
    - mastodon.py
    - psycopg
    - pyiem >=1.26
    - pymemcache
    - requests
    - service-identity
    - twisted >=18.4

test:
  imports:
    - iembot
  commands:
    - pip check
    - iembot --help
    - iembot run --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: An XMPP bot that moves weather data around and other things.
  home: https://github.com/akrherz/iembot
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
